### PR TITLE
Add files via upload

### LINKED ISSUE #32: Create a Scroll to top button
**Its icon** Must look like the image given below.
image

Deliverables:
1. Make the button as a **separate React component** and give it that scroll to top functionality
2. This is a dark themed website So design the button to suit the theme
3. It must be a **material-ui IconButton** component

Remember on thing, to make the button appear only when user has scrolled down more the 400px (i.e `window.pageYOffset > 400`)

Use arrow icon from `@material-ui/icons`

### PR DESCRIPTION
**Pull request by vmk8826**
closes #32 

I have created the go-to top button as you wanted. Please check the code and freely contact me for any changes required.

### CODE REVIEW

**Review by ashuvssut — COMMENTED** [review]
Hey there!

Thanks for the PR. Please ensure that you strictly follow the deliverables i requested in #32 

You need to create a react component for scroll to top button

Happy Learning!

**Comment by ashuvssut** [comment]
I have changed this PR's base branch to `dev` branch instead of `main`

kindly give your future PRs in dev branch only

**Comment by ashuvssut** [comment]
good first issues are made for beginners. If you need help please ask.😁

**Comment by vmk8826** [comment]
okay

**Comment by ashuvssut** [comment]
Your design is all okay🙂. 

But that button should ideally hide whenever `window.pageYOffset < 400`

**Comment by ashuvssut** [comment]
check this one out: https://github.com/smaranjitghose/doc2pen/blob/master/src/components/ScrollToTopButton/ScrollToTopButton.jsx

It uses bootstrap design instead of materialui.
Refer this if you get stuck. its a react component

**Comment by vmk8826** [comment]
okay

**Pull request closed without merging**
