### PR TITLE
add scroll to top button

### PR DESCRIPTION
**Pull request by Starboy-Sharma**
Scroll to the top button add to the Home Page. Fix issue #32

### CODE REVIEW

**Comment by namrataaaa** [comment]
Rename your file to Scroll.jsx instead of Scroll.tsx. And change the style of the button to 'right: -10px' and see the change. Try to make the button floating which will appear whenever users start to scrolls down any page. And you may place it on the bottom right side of the screen because most users use their right hand's thumb to scroll.

**Comment by Starboy-Sharma** [comment]
Okay @namrataaaa  I will do the same and update my code

**Comment by Starboy-Sharma** [comment]
The scroll component is updated. I think my CSS is override for some reason that's why component is not working correctly. Please check now.

**Comment by namrataaaa** [comment]
Good work 👍

**Pull request merged**
