### PR TITLE
Team section

### PR DESCRIPTION
**Pull request by ashuvssut**

### CODE REVIEW

**Comment by ashuvssut** [comment]
@chandrasekhar2039 review the code. check if I havent made any undesired changes to the files that you have told not to touch

**Comment by chandrasekhar2039** [comment]
yes grt job ... wait for the vercel deployment failure to fixed then you can proceed

**Comment by chandrasekhar2039** [comment]
@ashuvssut dont get confused by the label .... your code is ok ... its the issue is in the bot .... once its cleared your pr will be merged

**Review by chandrasekhar2039 — APPROVED** [review]

**Comment by ashuvssut** [comment]
> @ashuvssut dont get confused by the label .... your code is ok ... its the issue is in the bot .... once its cleared your pr will be merged

I know that thing. I was just asking a peer review. Its just to inform you that what change are gonna be merged

**Comment by chandrasekhar2039** [comment]
Abe merge error thik haba  pare merge karibara thila be ... ufffhooo 🤦‍♂️..... chade nxt time dhayan rakhibu.... label dekhibu hela .... other than that nice wrk buddy

**Pull request merged**
